services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    env_file:
      - .env
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:

networks:
  inception:
