services:
  static_web:
    build: requirements/bonus/static_web/.
    container_name: static_web
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  ftp:
    build: requirements/bonus/ftp/.
    container_name: ftp
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  redis:
    build: requirements/bonus/redis/.
    container_name: redis
    volumes:
      - ./web:/var/www/html
    ports:
      - "6379:6379"
    networks:
      inception:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file:
      - .env
    depends_on:
      - redis
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    env_file:
      - .env
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:

networks:
  inception:
